name: test
on: [push, pull_request]
env:
  CI: true
  NODE_VERSION: 18
permissions:
  contents: read
jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]
        os: [macos-latest, windows-latest, ubuntu-latest]
        exclude:
          # mac tests is expensive, limit to 1 instance
          - os: macos-latest
            node-version: 16
          - os: macos-latest
            node-version: 18
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run lint && yarn test
      - name: Run E2E
        run: yarn run build
        working-directory: examples/benchmark

  docker-image:
    name: "Build docker image and generate pdf"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker buildx build -t testing --build-arg NODE_VERSION=${NODE_VERSION} ./docker
      - name: Generate pdf
        run: docker run -v `pwd`/examples/book:/work -w /work --rm testing honkit pdf
